package buildconfig

import (
	"crypto/sha256"
	"encoding/hex"
	"regexp"
	"strings"
)

const (
	// maxGeneratedNameLength is the maximum length for names generated by the
	// converter. The DNS-1123 label limit (63) is used rather than the DNS-1123
	// subdomain limit (253) because Shipwright derives BuildRun, Pod, and label
	// values from these names by appending suffixes.
	maxGeneratedNameLength = 63

	// nameHashLength is the number of hex characters of the SHA-256 digest of
	// the original name appended when a name has to be rewritten.
	nameHashLength = 8
)

var invalidDNS1123LabelChars = regexp.MustCompile(`[^a-z0-9-]+`)

// sanitizeDNS1123Label converts name into a valid DNS-1123 label of at most
// maxGeneratedNameLength characters. The second return value reports whether
// the name had to be changed.
//
// When a change is required (invalid characters or excessive length), a
// deterministic hash suffix derived from the original name is appended. This
// keeps results stable across plugin invocations and guarantees that two
// distinct originals cannot collide after truncation to the same prefix.
func sanitizeDNS1123Label(name string) (string, bool) {
	s := strings.ToLower(name)
	s = invalidDNS1123LabelChars.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == name && len(s) <= maxGeneratedNameLength {
		return name, false
	}
	return withHashSuffix(s, name), true
}

// withHashSuffix appends "-<hash>" to base, where the hash is deterministically
// derived from original, truncating base so the result fits within
// maxGeneratedNameLength characters.
func withHashSuffix(base, original string) string {
	sum := sha256.Sum256([]byte(original))
	suffix := "-" + hex.EncodeToString(sum[:])[:nameHashLength]
	maxBase := maxGeneratedNameLength - len(suffix)
	if len(base) > maxBase {
		base = base[:maxBase]
	}
	base = strings.Trim(base, "-")
	if base == "" {
		base = "bc"
	}
	return base + suffix
}
